services:
  frontend:
    image: retuc907/frontend-react:latest
    build:
      context: .
      args:
        VITE_API_URL: http://localhost:8080/api
    container_name: frontend-academica
    ports:
      - "8081:80"